export const addresses = [
  {
    id: 1,
    name: 'Priya Sharma',
    streetAddress: 'Mannerheimintie 12',
    city: 'Helsinki',
    phoneCode: '+358',
    phoneNumber: '401234567',
    state: 'Uusimaa',
    zipCode: '00100',
    isDefault: true,
  },
  {
    id: 2,
    name: 'Rajesh Kumar',
    streetAddress: 'Otaniementie 5',
    city: 'Espoo',
    phoneCode: '+358',
    phoneNumber: '501234567',
    state: 'Uusimaa',
    zipCode: '02150',
  },
  {
    id: 3,
    name: 'Anita Patel',
    streetAddress: 'Tikkurilantie 8',
    city: 'Vantaa',
    phoneCode: '+358',
    phoneNumber: '441234567',
    state: 'Uusimaa',
    zipCode: '01300',
  },
];
